apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: canal-web
  description: Canal web corporativo para clientes
  tags:
    - channel
    - frontend
    - customer
spec:
  type: website
  lifecycle: production
  owner: group:default/team-canales
  system: canales-digitales
  dependsOn:
    - component:default/api-clientes-aws
